modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU LGPLv3"
[[mods]]
modId = "felnullservermod"
version = "${file.jarVersion}"
displayName = "FelNull Server MOD"
credits = "TeamFelNull"
authors = "MORIMORI0317"
description = '''
The Ikisugi FelNull Server MOD
'''
